apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-build-params
spec:
  params:
    - name: SOURCE_ARTIFACT
      type: string
      description: >-
        The Trusted Artifact URI pointing to the artifact with the application source code.
  results:
    - name: annotations
      type: array
      description: ANNOTATIONS array for buildah
    - name: labels
      type: array
      description: LABELS array for buildah
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:5307eb0dd71e493851632526497b85640efe46cf2e1934856724489260c968ae
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/tekton/home/source

    - name: set-results
      image: registry.access.redhat.com/ubi10/ubi-minimal:10.1@sha256:a13cec4e2e30fa2ca6468d474d02eb349200dc4a831c8c93f05a2154c559f09b
      env:
        - name: ANNOTATIONS_RESULT
          value: $(results.annotations.path)
        - name: LABELS_RESULT
          value: $(results.labels.path)
      workingDir: /tekton/home/source
      script: |
        #!/bin/bash
        set -euo pipefail

        version=$(cat VERSION)

        printf '["org.opencontainers.image.version=%s"]' "$version" > "$ANNOTATIONS_RESULT"
        printf '["org.opencontainers.image.version=%s"]' "$version" > "$LABELS_RESULT"
